yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
version: 3
final_space: true

palette:
  iris-main: "#c4a7e7"
  pine-blue-moon: "#3e8fb0"
  foam-moon: "#9ccfd8"
  love-moon: "#eb6f92"
  rose-moon: "#ea9a97"

blocks:
- type: prompt
  style: plain
  alignment: left
  newline: true
  segments:
    - type: path
      template: "{{ .PWD }}"
      foreground: p:pine-blue-moon
      properties:
        cache_duration: none
        style: full

    - type: python
      style: powerline
      powerline_symbol: 
      foreground: "#100e23"
      background: "#906cff"
      template: "  {{ .Full }} "


    - type: git
      style: powerline
      foreground: p:rose-moon

- type: prompt
  alignment: left
  newline: true
  segments:
  - properties:
      cache_duration: none
    template: '🢖'
    foreground: p:iris-main
    type: text

- type: rprompt
  segments:
    - type: executiontime


transient_prompt:
  background: transparent
  foreground_templates: [
    "{{ if gt .Code 0 }}p:love-moon{{end}}",
    "{{ if eq .Code 0 }}p:foam-moon{{end}}",
  ]
  template: '🢖 '
  foreground: p:iris-main
