# Hyprpaper config
# Preload wallpapers so waypaper can switch them instantly

preload = ~/wallpaper/anime/monkey-d-luffy-1920x1200-16712.jpg
wallpaper = ,~/wallpaper/anime/monkey-d-luffy-1920x1200-16712.jpg
